TOOLCHAIN=../../toolchain
CXX=$(TOOLCHAIN)/x86_64-unknown-linux-gnu-4.8.1-2.9-2.20-2.6.32/bin/x86_64-unknown-linux-gnu-c++
CXX_FLAG=-std=gnu++11 -Wall
SOURCES=print_test.cpp
test_print:
	$(CXX) $(SOURCES) -o $@ $(CXX_FLAG) 
