all:
	g++ glog_test.cpp -o glog_test -std=c++11 -I/usr/local/opt/glog/include /usr/local/opt/glog/lib/libglog.dylib -I/usr/local/opt/gflags/include /usr/local/opt/gflags/lib/libgflags.dylib
clean:
	@rm glog_test
